input {
  file {
    path => "/logs/*.jsonl"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sentinelflow-logstash.sincedb"
    codec => json
  }
}
filter {
  mutate { add_field => { "service" => "sentinelflow-api" } }
}
output {
  elasticsearch { hosts => ["http://elasticsearch:9200"] index => "sentinelflow-%{+YYYY.MM.dd}" }
}
